### ISSUE TITLE
1.20.1 Error for incompatible Fabric version

### ISSUE THREAD

**Issue by tierbee** [jbossjaslow/HorseWhistle#4]
When I try using Horse Whistle for 1.20.1, it says that I need fabric api 91.9+1.20.1 but the latest version for 1.20.1 is listed as 91.0+1.20.1 and no 91.9+1.20.1 appears as a past version. Any idea why this happens? 
![image](https://github.com/jbossjaslow/HorseWhistle/assets/118947183/e578afc4-dc07-4b15-92ee-154530471b8e)

**Comment by jbossjaslow** [comment]
Not sure where I got that version from. I never had problems myself, but I've adjusted it to hopefully clear up your problems. Let me know if it's still broken.
